social-bar-new-tab
i-pranav/ACDLadders pull request #13
Opened 2023-07-02 11:59 UTC by lokesh783

I have done the changes, added target="_blank" for ACodeDaily social account links, as the code was not working in my system, so I need to install some dependencies, please check them before merge.

2023-07-04 15:09 UTC, thoughtlessnerd requested changes

2023-07-04 15:09 UTC, thoughtlessnerd commented on frontend/package-lock.json
don't update the package-lock.json, every computer has different package-lock.json file so its not a good practice to update package-lock, so remove it please from the PR

2023-07-04 15:09 UTC, thoughtlessnerd commented on package-lock.json
same here, remove this one too

2023-07-04 15:09 UTC, thoughtlessnerd commented on package.json
this won't cause any issue but just telling the @types/react is not supposed to be a devDependency as during production phase devDependencies get ignored and without @types/react it will cause major errors and will break completely so take care from next time

2023-07-06 18:10 UTC, i-pranav commented
please resolve this asap.

2023-07-07 03:55 UTC, closed without merging